import { pgTable, serial, text, real, timestamp, boolean } from 'drizzle-orm/pg-core'

// One row per sensor reading generated by the simulation loop.
export const readings = pgTable('readings', {
  id: serial().primaryKey(),
  timestamp: timestamp('timestamp').defaultNow().notNull(),
  corrente: real().notNull(),
  temperatura: real().notNull(),
  vibracao: real().notNull(),
  rotacao: real().notNull(),
})

// A self-contained historical record of any non-normal reading. Captures the
// range/attention-band that was active at the moment of the reading so this
// table stays accurate forever, even if ranges are edited later (no live
// join against `ranges`).
export const failures = pgTable('failures', {
  id: serial().primaryKey(),
  timestamp: timestamp('timestamp').defaultNow().notNull(),
  variable: text('variable').notNull(), // corrente | temperatura | vibracao | rotacao
  value: real().notNull(),
  unit: text('unit').notNull(),
  status: text('status').notNull(), // attention | alarm
  min: real().notNull(),
  max: real().notNull(),
  attentionBand: real('attention_band').notNull(),
})

// Every login attempt, successful or not.
export const accessLogs = pgTable('access_logs', {
  id: serial().primaryKey(),
  timestamp: timestamp('timestamp').defaultNow().notNull(),
  userLabel: text('user_label').notNull(), // e.g. "Operador" / "Suporte"
  role: text('role').notNull(),
  success: boolean().notNull(),
})

// One row per sensor variable holding the currently configured range.
export const ranges = pgTable('ranges', {
  variable: text('variable').primaryKey(), // corrente | temperatura | vibracao | rotacao
  min: real().notNull(),
  max: real().notNull(),
  attentionBand: real('attention_band').notNull(),
})
