import {
  pgTable,
  serial,
  text,
  real,
  timestamp,
  boolean,
  integer,
  primaryKey,
} from 'drizzle-orm/pg-core'

// Each monitored motor. All motors share the same four measurement types.
// Motor 1 is seeded by migration; existing readings/failures default to it.
export const motors = pgTable('motors', {
  id: serial().primaryKey(),
  name: text().notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})

// One row per sensor reading generated by the simulation loop.
export const readings = pgTable('readings', {
  id: serial().primaryKey(),
  timestamp: timestamp('timestamp').defaultNow().notNull(),
  motorId: integer('motor_id').notNull().default(1),
  corrente: real().notNull(),
  temperatura: real().notNull(),
  vibracao: real().notNull(),
  rotacao: real().notNull(),
})

// A self-contained historical record of any non-normal reading. Captures the
// range/attention-band that was active at the moment of the reading so this
// table stays accurate forever, even if ranges are edited later (no live
// join against `ranges`).
export const failures = pgTable('failures', {
  id: serial().primaryKey(),
  timestamp: timestamp('timestamp').defaultNow().notNull(),
  motorId: integer('motor_id').notNull().default(1),
  variable: text('variable').notNull(), // corrente | temperatura | vibracao | rotacao
  value: real().notNull(),
  unit: text('unit').notNull(),
  status: text('status').notNull(), // attention | alarm
  min: real().notNull(),
  max: real().notNull(),
  attentionBand: real('attention_band').notNull(),
})

// Every login attempt, successful or not, plus every screen (aba) visited by
// a logged-in user (`event = 'page'`, with the screen path in `page`).
export const accessLogs = pgTable('access_logs', {
  id: serial().primaryKey(),
  timestamp: timestamp('timestamp').defaultNow().notNull(),
  userLabel: text('user_label').notNull(), // e.g. "Operador" / "Suporte"
  role: text('role').notNull(),
  success: boolean().notNull(),
  event: text('event').notNull().default('login'), // login | page
  page: text('page'),
})

// Legacy single-motor ranges. Kept for backwards compatibility; its values
// were copied into `motor_ranges` for Motor 1. New code uses `motorRanges`.
export const ranges = pgTable('ranges', {
  variable: text('variable').primaryKey(), // corrente | temperatura | vibracao | rotacao
  min: real().notNull(),
  max: real().notNull(),
  attentionBand: real('attention_band').notNull(),
})

// Currently configured range per motor + sensor variable.
export const motorRanges = pgTable(
  'motor_ranges',
  {
    motorId: integer('motor_id')
      .notNull()
      .references(() => motors.id, { onDelete: 'cascade' }),
    variable: text('variable').notNull(), // corrente | temperatura | vibracao | rotacao
    min: real().notNull(),
    max: real().notNull(),
    attentionBand: real('attention_band').notNull(),
  },
  (t) => [primaryKey({ columns: [t.motorId, t.variable] })],
)

// Maintenance performed on a motor, registered by Suporte.
export const maintenances = pgTable('maintenances', {
  id: serial().primaryKey(),
  motorId: integer('motor_id').notNull(),
  motorName: text('motor_name').notNull(), // snapshot, stays readable if renamed
  performedAt: timestamp('performed_at').notNull(), // quando foi feita
  description: text().notNull(), // o que foi feito
  reason: text().notNull(), // por que foi feita
  createdBy: text('created_by').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
})
